// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ9sjPzeUzto8QXE0Xn3q6hBXRJpS2yKs',
    appId: '1:252146025977:web:923ea924a15295bc066928',
    messagingSenderId: '252146025977',
    projectId: 'heychat2-bacc3',
    authDomain: 'heychat2-bacc3.firebaseapp.com',
    storageBucket: 'heychat2-bacc3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGoEacVqe9gAftBpjXFxXD0rIYufFUOF0',
    appId: '1:252146025977:android:04e87eb068089015066928',
    messagingSenderId: '252146025977',
    projectId: 'heychat2-bacc3',
    storageBucket: 'heychat2-bacc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEq4RwpkSFHBhtyNiflTvJt2dd2v2pCME',
    appId: '1:252146025977:ios:d51872e31b2797e4066928',
    messagingSenderId: '252146025977',
    projectId: 'heychat2-bacc3',
    storageBucket: 'heychat2-bacc3.appspot.com',
    iosBundleId: 'com.ogulcankacar.heychat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEq4RwpkSFHBhtyNiflTvJt2dd2v2pCME',
    appId: '1:252146025977:ios:d51872e31b2797e4066928',
    messagingSenderId: '252146025977',
    projectId: 'heychat2-bacc3',
    storageBucket: 'heychat2-bacc3.appspot.com',
    iosBundleId: 'com.ogulcankacar.heychat2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ9sjPzeUzto8QXE0Xn3q6hBXRJpS2yKs',
    appId: '1:252146025977:web:d84035b8e1dc78ff066928',
    messagingSenderId: '252146025977',
    projectId: 'heychat2-bacc3',
    authDomain: 'heychat2-bacc3.firebaseapp.com',
    storageBucket: 'heychat2-bacc3.appspot.com',
  );
}
